"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { use } from "react";

type BlogPost = {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  category: string;
  tags: string[];
  metaTitle: string | null;
  metaDescription: string | null;
  keywords: string[];
  comparisonSlug: string | null;
  status: string;
  autoGenerated: boolean;
  publishedAt: string | null;
  scheduledFor: string | null;
  authorNote: string | null;
  generatedPrompt: string | null;
  readTimeMinutes: number;
  viewCount: number;
  createdAt: string;
  updatedAt: string;
};

export default function BlogPostReview({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = use(params);
  const router = useRouter();
  const [post, setPost] = useState<BlogPost | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [editedContent, setEditedContent] = useState("");
  const [editedTitle, setEditedTitle] = useState("");
  const [editedExcerpt, setEditedExcerpt] = useState("");
  const [authorNote, setAuthorNote] = useState("");
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchPost = async () => {
      setLoading(true);
      setError(null);
      try {
        const res = await fetch(`/api/admin/blog/posts/${resolvedParams.id}`);
        const data = await res.json();
        if (data.success) {
          setPost(data.post);
          setEditedContent(data.post.content);
          setEditedTitle(data.post.title);
          setEditedExcerpt(data.post.excerpt);
          setAuthorNote(data.post.authorNote || "");
        } else {
          setError(data.error || "Failed to load post");
        }
      } catch (err) {
        console.error("Failed to fetch post:", err);
        setError("Failed to fetch post. Please try again.");
      } finally {
        setLoading(false);
      }
    };

    fetchPost();
  }, [resolvedParams.id]);

  const refetchPost = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch(`/api/admin/blog/posts/${resolvedParams.id}`);
      const data = await res.json();
      if (data.success) {
        setPost(data.post);
        setEditedContent(data.post.content);
        setEditedTitle(data.post.title);
        setEditedExcerpt(data.post.excerpt);
        setAuthorNote(data.post.authorNote || "");
      } else {
        setError(data.error || "Failed to load post");
      }
    } catch (err) {
      console.error("Failed to fetch post:", err);
      setError("Failed to fetch post. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const saveChanges = async () => {
    setSaving(true);
    try {
      const res = await fetch(`/api/admin/blog/posts/${resolvedParams.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: editedTitle,
          excerpt: editedExcerpt,
          content: editedContent,
          authorNote,
        }),
      });
      const data = await res.json();
      if (data.success) {
        alert("✅ Changes saved!");
        setPost(data.post);
      }
    } catch (error) {
      console.error("Failed to save:", error);
      alert("❌ Failed to save changes");
    } finally {
      setSaving(false);
    }
  };

  const updateStatus = async (status: string) => {
    try {
      const res = await fetch(`/api/admin/blog/posts/${resolvedParams.id}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ status }),
      });
      const data = await res.json();
      if (data.success) {
        setPost(data.post);
        if (status === "published") {
          alert("✅ Post published!");
          router.push(`/blog/${data.post.slug}`);
        } else {
          alert(`✅ Status updated to ${status}`);
        }
      }
    } catch (error) {
      console.error("Failed to update status:", error);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="text-gray-500 text-lg mb-2">Loading post...</div>
          <div className="text-sm text-gray-400">Please wait</div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center max-w-md">
          <div className="text-red-500 text-lg mb-4">⚠️ {error}</div>
          <button
            onClick={() => window.location.reload()}
            className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
          >
            Retry
          </button>
          <div className="mt-4">
            <a
              href="/admin/blog"
              className="text-blue-600 hover:text-blue-900"
            >
              ← Back to Dashboard
            </a>
          </div>
        </div>
      </div>
    );
  }

  if (!post) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center max-w-md">
          <div className="text-red-500 text-lg mb-4">Post not found</div>
          <a
            href="/admin/blog"
            className="inline-block px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
          >
            ← Back to Dashboard
          </a>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-8 flex items-center justify-between">
          <div>
            <button
              onClick={() => router.push("/admin/blog")}
              className="text-blue-600 hover:text-blue-900 mb-2"
            >
              ← Back to Dashboard
            </button>
            <h1 className="text-3xl font-bold text-gray-900">Review Blog Post</h1>
            <p className="mt-2 text-gray-600">
              {post.autoGenerated ? "AI-Generated Post" : "Manual Post"}
            </p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={saveChanges}
              disabled={saving}
              className="px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700 disabled:opacity-50"
            >
              {saving ? "Saving..." : "Save Changes"}
            </button>
            {post.status === "pending_review" && (
              <>
                <button
                  onClick={() => updateStatus("approved")}
                  className="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700"
                >
                  ✓ Approve
                </button>
                <button
                  onClick={() => updateStatus("rejected")}
                  className="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700"
                >
                  ✗ Reject
                </button>
              </>
            )}
            {post.status === "approved" && (
              <button
                onClick={() => updateStatus("published")}
                className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
              >
                🚀 Publish Now
              </button>
            )}
          </div>
        </div>

        {/* Post Details */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-6">
            {/* Title */}
            <div className="bg-white shadow rounded-lg p-6">
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Title
              </label>
              <input
                type="text"
                value={editedTitle}
                onChange={(e) => setEditedTitle(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>

            {/* Excerpt */}
            <div className="bg-white shadow rounded-lg p-6">
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Excerpt
              </label>
              <textarea
                value={editedExcerpt}
                onChange={(e) => setEditedExcerpt(e.target.value)}
                rows={3}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>

            {/* Content */}
            <div className="bg-white shadow rounded-lg p-6">
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Content (Markdown)
              </label>
              <textarea
                value={editedContent}
                onChange={(e) => setEditedContent(e.target.value)}
                rows={25}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono text-sm"
              />
            </div>

            {/* Author Notes */}
            <div className="bg-white shadow rounded-lg p-6">
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Your Notes (Private)
              </label>
              <textarea
                value={authorNote}
                onChange={(e) => setAuthorNote(e.target.value)}
                rows={3}
                placeholder="Add any notes about this post..."
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
            </div>
          </div>

          {/* Sidebar */}
          <div className="space-y-6">
            {/* Status */}
            <div className="bg-white shadow rounded-lg p-6">
              <h3 className="text-lg font-medium text-gray-900 mb-4">Status</h3>
              <div className="space-y-2">
                <div className="flex justify-between">
                  <span className="text-gray-600">Current:</span>
                  <span className="font-medium">{post.status}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Views:</span>
                  <span className="font-medium">{post.viewCount}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-gray-600">Read Time:</span>
                  <span className="font-medium">{post.readTimeMinutes} min</span>
                </div>
              </div>
            </div>

            {/* Metadata */}
            <div className="bg-white shadow rounded-lg p-6">
              <h3 className="text-lg font-medium text-gray-900 mb-4">Metadata</h3>
              <div className="space-y-3">
                <div>
                  <div className="text-sm font-medium text-gray-500">Category</div>
                  <div className="mt-1">{post.category}</div>
                </div>
                <div>
                  <div className="text-sm font-medium text-gray-500">Tags</div>
                  <div className="mt-1 flex flex-wrap gap-2">
                    {post.tags.map((tag) => (
                      <span
                        key={tag}
                        className="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-blue-100 text-blue-800"
                      >
                        {tag}
                      </span>
                    ))}
                  </div>
                </div>
                <div>
                  <div className="text-sm font-medium text-gray-500">Keywords</div>
                  <div className="mt-1 text-sm text-gray-700">
                    {post.keywords.join(", ")}
                  </div>
                </div>
              </div>
            </div>

            {/* SEO */}
            <div className="bg-white shadow rounded-lg p-6">
              <h3 className="text-lg font-medium text-gray-900 mb-4">SEO</h3>
              <div className="space-y-3">
                <div>
                  <div className="text-sm font-medium text-gray-500">Meta Title</div>
                  <div className="mt-1 text-sm text-gray-700">{post.metaTitle}</div>
                </div>
                <div>
                  <div className="text-sm font-medium text-gray-500">
                    Meta Description
                  </div>
                  <div className="mt-1 text-sm text-gray-700">
                    {post.metaDescription}
                  </div>
                </div>
              </div>
            </div>

            {/* Related Comparison */}
            {post.comparisonSlug && (
              <div className="bg-white shadow rounded-lg p-6">
                <h3 className="text-lg font-medium text-gray-900 mb-4">
                  Related Comparison
                </h3>
                <a
                  href={`/compare/${post.comparisonSlug}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 hover:text-blue-900"
                >
                  View Comparison →
                </a>
              </div>
            )}

            {/* AI Prompt (for debugging) */}
            {post.generatedPrompt && (
              <div className="bg-white shadow rounded-lg p-6">
                <h3 className="text-lg font-medium text-gray-900 mb-4">
                  AI Prompt Used
                </h3>
                <div className="text-xs text-gray-600 font-mono bg-gray-50 p-3 rounded max-h-40 overflow-y-auto">
                  {post.generatedPrompt.slice(0, 300)}...
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
