"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

export default function NewBlogPost() {
  const router = useRouter();
  const [saving, setSaving] = useState(false);
  const [formData, setFormData] = useState({
    title: "",
    excerpt: "",
    content: "",
    category: "Technology",
    tags: "",
    metaTitle: "",
    metaDescription: "",
    keywords: "",
    readTimeMinutes: 5,
  });

  const categories = [
    "Technology",
    "Business",
    "Entertainment",
    "Health",
    "Lifestyle",
    "Finance",
    "Education",
    "Sports",
    "Gaming",
    "Automotive",
    "Science",
    "General",
  ];

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);

    try {
      const payload = {
        ...formData,
        tags: formData.tags.split(",").map((t) => t.trim()).filter(Boolean),
        keywords: formData.keywords.split(",").map((k) => k.trim()).filter(Boolean),
        autoGenerated: false,
        status: "draft",
      };

      const res = await fetch("/api/admin/blog/posts/create", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      const data = await res.json();

      if (data.success) {
        alert("✅ Post created successfully!");
        router.push(`/admin/blog/${data.postId}`);
      } else {
        alert(`❌ Failed to create post: ${data.error}`);
      }
    } catch (err) {
      console.error("Failed to create post:", err);
      alert("❌ Failed to create post. Please try again.");
    } finally {
      setSaving(false);
    }
  };

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>
  ) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  return (
    <div className="min-h-screen bg-gray-50 py-4 sm:py-8">
      <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <div className="mb-6 sm:mb-8">
          <button
            onClick={() => router.back()}
            className="text-blue-600 hover:text-blue-900 mb-2 sm:mb-4 text-sm sm:text-base"
          >
            ← Back to Dashboard
          </button>
          <h1 className="text-2xl sm:text-3xl font-bold text-gray-900">Create New Blog Post</h1>
          <p className="mt-1 sm:mt-2 text-sm sm:text-base text-gray-600">
            Write your own blog post manually
          </p>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Title */}
          <div className="bg-white shadow rounded-lg p-4 sm:p-6">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Title *
            </label>
            <input
              type="text"
              name="title"
              value={formData.title}
              onChange={handleChange}
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="Enter post title (60-70 characters recommended)"
              required
              maxLength={100}
            />
            <p className="mt-1 text-xs text-gray-500">{formData.title.length}/100 characters</p>
          </div>

          {/* Excerpt */}
          <div className="bg-white shadow rounded-lg p-4 sm:p-6">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Excerpt *
            </label>
            <textarea
              name="excerpt"
              value={formData.excerpt}
              onChange={handleChange}
              rows={3}
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="Brief summary of the post (150-160 characters recommended)"
              required
              maxLength={250}
            />
            <p className="mt-1 text-xs text-gray-500">{formData.excerpt.length}/250 characters</p>
          </div>

          {/* Content */}
          <div className="bg-white shadow rounded-lg p-4 sm:p-6">
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Content (Markdown) *
            </label>
            <textarea
              name="content"
              value={formData.content}
              onChange={handleChange}
              rows={20}
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 font-mono text-sm"
              placeholder="Write your blog post in Markdown format...&#10;&#10;## Heading 2&#10;### Heading 3&#10;&#10;- Bullet point&#10;- Another point&#10;&#10;**Bold text**"
              required
            />
            <p className="mt-1 text-xs text-gray-500">
              Use Markdown formatting: ## for headings, **bold**, - for lists
            </p>
          </div>

          {/* Category & Tags */}
          <div className="bg-white shadow rounded-lg p-4 sm:p-6 space-y-4">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Category *
                </label>
                <select
                  name="category"
                  value={formData.category}
                  onChange={handleChange}
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                  required
                >
                  {categories.map((cat) => (
                    <option key={cat} value={cat}>
                      {cat}
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Read Time (minutes)
                </label>
                <input
                  type="number"
                  name="readTimeMinutes"
                  value={formData.readTimeMinutes}
                  onChange={handleChange}
                  min="1"
                  max="60"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                />
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Tags (comma-separated)
              </label>
              <input
                type="text"
                name="tags"
                value={formData.tags}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="e.g., ai, trends, comparison"
              />
            </div>
          </div>

          {/* SEO */}
          <div className="bg-white shadow rounded-lg p-4 sm:p-6 space-y-4">
            <h3 className="text-lg font-medium text-gray-900">SEO Settings</h3>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Meta Title
              </label>
              <input
                type="text"
                name="metaTitle"
                value={formData.metaTitle}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="SEO title (defaults to main title if empty)"
                maxLength={70}
              />
              <p className="mt-1 text-xs text-gray-500">{formData.metaTitle.length}/70 characters</p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Meta Description
              </label>
              <textarea
                name="metaDescription"
                value={formData.metaDescription}
                onChange={handleChange}
                rows={2}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="SEO description (defaults to excerpt if empty)"
                maxLength={160}
              />
              <p className="mt-1 text-xs text-gray-500">{formData.metaDescription.length}/160 characters</p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Keywords (comma-separated)
              </label>
              <input
                type="text"
                name="keywords"
                value={formData.keywords}
                onChange={handleChange}
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="e.g., trend analysis, comparison, insights"
              />
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-3 sticky bottom-4 bg-white shadow-lg rounded-lg p-4 border border-gray-200">
            <button
              type="submit"
              disabled={saving}
              className="flex-1 sm:flex-none sm:px-6 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {saving ? "Creating..." : "Create Post"}
            </button>
            <button
              type="button"
              onClick={() => router.back()}
              className="flex-1 sm:flex-none sm:px-6 py-2 bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300"
            >
              Cancel
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
