import { NextResponse } from "next/server";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

/**
 * GET /api/admin/blog/posts
 * Get all blog posts with filtering
 */
export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const status = searchParams.get("status");

    const where = status ? { status } : {};

    const posts = await prisma.blogPost.findMany({
      where,
      orderBy: { createdAt: "desc" },
      select: {
        id: true,
        slug: true,
        title: true,
        excerpt: true,
        category: true,
        status: true,
        autoGenerated: true,
        publishedAt: true,
        scheduledFor: true,
        createdAt: true,
        updatedAt: true,
        viewCount: true,
        tags: true,
      },
    });

    // Calculate stats
    const stats = {
      total: await prisma.blogPost.count(),
      published: await prisma.blogPost.count({ where: { status: "published" } }),
      pending: await prisma.blogPost.count({ where: { status: "pending_review" } }),
      draft: await prisma.blogPost.count({ where: { status: "draft" } }),
    };

    return NextResponse.json({ success: true, posts, stats });
  } catch (error) {
    console.error("[API] Failed to fetch posts:", error);
    return NextResponse.json(
      { success: false, error: "Failed to fetch posts" },
      { status: 500 }
    );
  }
}
