import { NextResponse } from "next/server";
import { PrismaClient } from "@prisma/client";
import slugify from "slugify";

const prisma = new PrismaClient();

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const {
      title,
      excerpt,
      content,
      category,
      tags = [],
      metaTitle,
      metaDescription,
      keywords = [],
      readTimeMinutes = 5,
      autoGenerated = false,
      status = "draft",
    } = body;

    // Validation
    if (!title || !excerpt || !content || !category) {
      return NextResponse.json(
        { success: false, error: "Missing required fields" },
        { status: 400 }
      );
    }

    // Generate slug from title
    const slug = slugify(title, {
      lower: true,
      strict: true,
      remove: /[*+~.()'"!:@]/g,
    });

    // Check if slug already exists
    const existing = await prisma.blogPost.findUnique({
      where: { slug },
    });

    if (existing) {
      // Add timestamp to make unique
      const uniqueSlug = `${slug}-${Date.now()}`;
      const post = await prisma.blogPost.create({
        data: {
          slug: uniqueSlug,
          title,
          excerpt,
          content,
          category,
          tags,
          metaTitle: metaTitle || title,
          metaDescription: metaDescription || excerpt,
          keywords,
          readTimeMinutes,
          autoGenerated,
          status,
        },
      });

      return NextResponse.json({ success: true, postId: post.id });
    }

    const post = await prisma.blogPost.create({
      data: {
        slug,
        title,
        excerpt,
        content,
        category,
        tags,
        metaTitle: metaTitle || title,
        metaDescription: metaDescription || excerpt,
        keywords,
        readTimeMinutes,
        autoGenerated,
        status,
      },
    });

    return NextResponse.json({ success: true, postId: post.id });
  } catch (error) {
    console.error("[API] Failed to create post:", error);
    return NextResponse.json(
      { success: false, error: "Failed to create post" },
      { status: 500 }
    );
  }
}
