// Amazon/E-commerce Product Categories
// Based on major Amazon categories and Keepa category IDs

export const PRODUCT_CATEGORIES = [
  { id: 'all', name: 'All Categories', icon: '🛍️' },
  { id: 'electronics', name: 'Electronics', icon: '📱' },
  { id: 'home-kitchen', name: 'Home & Kitchen', icon: '🏠' },
  { id: 'sports-outdoors', name: 'Sports & Outdoors', icon: '⚽' },
  { id: 'beauty-personal-care', name: 'Beauty & Personal Care', icon: '💄' },
  { id: 'toys-games', name: 'Toys & Games', icon: '🎮' },
  { id: 'clothing-shoes', name: 'Clothing & Shoes', icon: '👕' },
  { id: 'health-household', name: 'Health & Household', icon: '💊' },
  { id: 'tools-home-improvement', name: 'Tools & Home Improvement', icon: '🔧' },
  { id: 'pet-supplies', name: 'Pet Supplies', icon: '🐾' },
  { id: 'office-products', name: 'Office Products', icon: '📎' },
  { id: 'automotive', name: 'Automotive', icon: '🚗' },
  { id: 'baby', name: 'Baby', icon: '👶' },
  { id: 'arts-crafts', name: 'Arts & Crafts', icon: '🎨' },
  { id: 'garden-outdoor', name: 'Garden & Outdoor', icon: '🌱' },
] as const;

export type ProductCategoryId = typeof PRODUCT_CATEGORIES[number]['id'];

// Curated trending product keywords by category
// These are high-potential product niches based on market research
export const TRENDING_KEYWORDS_BY_CATEGORY: Record<string, string[]> = {
  'electronics': [
    'wireless earbuds',
    'phone stand',
    'power bank',
    'usb c cable',
    'phone case',
    'laptop stand',
    'wireless charger',
    'webcam',
    'bluetooth speaker',
    'ring light',
    'car phone holder',
    'screen protector',
    'hdmi cable',
    'portable monitor',
    'gaming mouse',
  ],
  'home-kitchen': [
    'air fryer',
    'coffee maker',
    'instant pot',
    'water filter',
    'kitchen knife set',
    'food storage containers',
    'spice rack',
    'can opener',
    'cutting board',
    'mixing bowls',
    'measuring cups',
    'kitchen scale',
    'dish rack',
    'pot holders',
    'trash can',
  ],
  'sports-outdoors': [
    'yoga mat',
    'resistance bands',
    'jump rope',
    'foam roller',
    'water bottle',
    'gym bag',
    'exercise ball',
    'dumbbells',
    'pull up bar',
    'yoga blocks',
    'bike lights',
    'camping tent',
    'hiking backpack',
    'sleeping bag',
    'portable hammock',
  ],
  'beauty-personal-care': [
    'hair dryer',
    'makeup brushes',
    'nail polish',
    'face mask',
    'hair straightener',
    'electric toothbrush',
    'facial cleanser',
    'moisturizer',
    'sunscreen',
    'hair clips',
    'makeup organizer',
    'nail file',
    'tweezers',
    'hair ties',
    'cotton pads',
  ],
  'toys-games': [
    'board games',
    'puzzles',
    'lego sets',
    'action figures',
    'dolls',
    'building blocks',
    'play dough',
    'coloring books',
    'stuffed animals',
    'toy cars',
    'nerf guns',
    'rc car',
    'kids tablet',
    'educational toys',
    'outdoor toys',
  ],
  'clothing-shoes': [
    'compression socks',
    'running shoes',
    'yoga pants',
    'sports bra',
    'tank tops',
    'hoodies',
    't shirts',
    'leggings',
    'athletic shorts',
    'sneakers',
    'sandals',
    'winter jacket',
    'baseball cap',
    'socks',
    'gloves',
  ],
  'health-household': [
    'vitamin d',
    'multivitamin',
    'protein powder',
    'probiotics',
    'fish oil',
    'hand sanitizer',
    'face masks medical',
    'thermometer',
    'heating pad',
    'first aid kit',
    'blood pressure monitor',
    'pulse oximeter',
    'massage gun',
    'knee brace',
    'back support',
  ],
  'tools-home-improvement': [
    'cordless drill',
    'screwdriver set',
    'hammer',
    'tape measure',
    'level tool',
    'utility knife',
    'work gloves',
    'flashlight',
    'tool bag',
    'safety glasses',
    'extension cord',
    'ladder',
    'paint brushes',
    'stud finder',
    'socket set',
  ],
  'pet-supplies': [
    'dog food',
    'cat litter',
    'pet bed',
    'dog toys',
    'cat toys',
    'leash',
    'collar',
    'pet carrier',
    'water bowl',
    'food bowl',
    'pet brush',
    'nail clippers',
    'pet shampoo',
    'litter box',
    'dog treats',
  ],
  'office-products': [
    'desk organizer',
    'pens',
    'notebooks',
    'sticky notes',
    'file folders',
    'binder clips',
    'stapler',
    'paper clips',
    'highlighters',
    'whiteboard',
    'markers',
    'desk lamp',
    'mouse pad',
    'keyboard',
    'monitor stand',
  ],
  'automotive': [
    'car phone mount',
    'dash cam',
    'car charger',
    'jumper cables',
    'tire pressure gauge',
    'car vacuum',
    'air freshener',
    'car seat covers',
    'windshield sun shade',
    'car cleaning kit',
    'floor mats',
    'steering wheel cover',
    'car organizer',
    'phone holder',
    'backup camera',
  ],
  'baby': [
    'baby bottles',
    'diapers',
    'baby wipes',
    'pacifiers',
    'baby monitor',
    'car seat',
    'stroller',
    'baby carrier',
    'changing pad',
    'baby clothes',
    'bibs',
    'teething toys',
    'baby blanket',
    'nursing pillow',
    'bottle warmer',
  ],
  'arts-crafts': [
    'acrylic paint',
    'paint brushes',
    'sketchbook',
    'colored pencils',
    'markers',
    'crayons',
    'glue gun',
    'scissors',
    'craft paper',
    'yarn',
    'knitting needles',
    'embroidery kit',
    'beads',
    'canvas',
    'clay',
  ],
  'garden-outdoor': [
    'garden hose',
    'watering can',
    'gardening gloves',
    'plant pots',
    'fertilizer',
    'pruning shears',
    'seed starter kit',
    'garden tools',
    'outdoor lights',
    'bird feeder',
    'compost bin',
    'lawn mower',
    'weed killer',
    'plant stakes',
    'soil',
  ],
};

// Get all unique keywords across all categories
export function getAllTrendingKeywords(): string[] {
  const allKeywords = Object.values(TRENDING_KEYWORDS_BY_CATEGORY).flat();
  return [...new Set(allKeywords)];
}

// Get keywords for a specific category
export function getKeywordsForCategory(categoryId: ProductCategoryId): string[] {
  if (categoryId === 'all') {
    return getAllTrendingKeywords();
  }
  return TRENDING_KEYWORDS_BY_CATEGORY[categoryId] || [];
}
